### ISSUE TITLE
playerbody collides when player is dead

### ISSUE THREAD

**Issue by DmitryTsyganov** [nochgames/server#10]
player exited 1
player number 1 is dead.
player exited 452
No such player! id: 1
/home/fatman/WebstormProjects/server/gamemechanics/chemistry/chemistry_advanced.js:76
        return player.resultDST(player.body, checkFunction, garbageBody)
                     ^

TypeError: Cannot read property 'resultDST' of undefined
    at ChemistryAdvanced.checkConnectingPossibilityGeneral (/home/fatman/WebstormProjects/server/gamemechanics/chemistry/chemistry_advanced.js:76:22)
    at ChemistryAdvanced.findBodyToConnect (/home/fatman/WebstormProjects/server/gamemechanics/chemistry/chemistry_advanced.js:125:21)
    at Object.CollisionHandler.collideWithGarbage (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:184:14)
    at Object.<anonymous> (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:28:22)
    at Object.Events.trigger (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4985:38)
    at Object.Engine.update (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4474:20)
    at null._repeat (/home/fatman/WebstormProjects/server/gamemechanics/index.js:415:27)
    at wrapper [as _onTimeout](timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DmitryTsyganov** [comment]
added deleteProperly to case 'player' in empty
