### ISSUE TITLE
Вылет сервера при стрельбе на пробел и попадании частицы в свой атом

### ISSUE THREAD

**Issue by ericovva** [nochgames/server#11]
/Users/erik/Desktop/NOCH_game/server/gamemechanics/chemistry/chemistry_advanced.js:120
        body.energy += bond[body.element];
                           ^

TypeError: Cannot read property 'C' of null
    at ChemistryAdvanced.balanceEnergy (/Users/erik/Desktop/NOCH_game/server/gamemechanics/chemistry/chemistry_advanced.js:120:28)
    at BasicParticle.free (/Users/erik/Desktop/NOCH_game/server/gamemechanics/basic particle/index.js:161:28)
    at Object.BasicParticle.traversDST (/Users/erik/Desktop/NOCH_game/server/gamemechanics/basic particle/index.js:68:9)
    at Object.BasicParticle.dismountBranch (/Users/erik/Desktop/NOCH_game/server/gamemechanics/basic particle/index.js:562:18)
    at Object.BasicParticle.changeCharge (/Users/erik/Desktop/NOCH_game/server/gamemechanics/basic particle/index.js:438:18)
    at Object.Player.shoot (/Users/erik/Desktop/NOCH_game/server/gamemechanics/player/index.js:84:39)
    at WebSocket.<anonymous> (/Users/erik/Desktop/NOCH_game/server/websocketservice/index.js:142:28)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/Users/erik/Desktop/NOCH_game/server/node_modules/ws/lib/WebSocket.js:816:10)

**Comment by DmitryTsyganov** [comment]
chemistry.balanceEnergy() in basicParticle.free() is called after element was changed. So balance energy returns null and no balancing happens.

**Comment by DmitryTsyganov** [comment]
На тест

**Comment by DmitryTsyganov** [comment]
#19

**Comment by DmitryTsyganov** [comment]
Crash from asking for impossible bond was prevented. But if bond is possible, wrong bond energy is subtracted, which leads to wrong element energy.
