### ISSUE TITLE
Вылет при присоединении игрока

### ISSUE THREAD

**Issue by DmitryTsyganov** [nochgames/server#25]
Игрок не найден, id -1175, но элемент поподает в collisionHandler как игрок либо его часть

**Comment by DmitryTsyganov** [comment]
No such player! id: -1175
players: 0,,,3,,
/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:94
                                                .body.position, garbageBody.position);
                                                ^

TypeError: Cannot read property 'body' of undefined
    at Object.CollisionHandler.createBond (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:94:49)
    at Object.CollisionHandler.connectGarbageToPlayer (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:143:14)
    at Object.CollisionHandler.collideWithGarbage (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:212:18)
    at Object.<anonymous> (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:33:22)
    at Object.Events.trigger (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4985:38)
    at Object.Engine.update (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4474:20)
    at null._repeat (/home/fatman/WebstormProjects/server/gamemechanics/index.js:606:27)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DmitryTsyganov** [comment]
No such player! id: -1175
players: ,,,,,5,6,,
playerBody: type garbage temporary undefined id -1175 garbageBody: type garbage temporary undefined id -1175

**Comment by DmitryTsyganov** [comment]
findBodyToConnect() возвращает мусор

**Comment by DmitryTsyganov** [comment]
constraint is here, but there is no parent though

Логично, если связано с этим. Ссылка нв родителя потеряна, но вот ссылка на ребёнка у родителя, видимо, осталась

**Comment by DmitryTsyganov** [comment]
Игрок умер в момент присоединения к нему частицы.

player died 653

Error: bodies are connected in a wrong way!
false garbageBody id 477 playerBody id 653
    at /home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:131:23
    at null._repeat (/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:508:21)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DmitryTsyganov** [comment]
![image](https://cloud.githubusercontent.com/assets/12236759/24840358/79c57cba-1d74-11e7-804e-213aeb6271b1.png)

player number 20 now sees 491
[ 184, 247, 410 ]
parent id 363
/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:137
                throw new Error("bodies are connected in a wrong way!\n" +
                ^

Error: bodies are connected in a wrong way!
false garbageBody id 301 playerBody id 485
    at CollisionHandler.createFinalCreateBond._stiffness (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:137:23)
    at null._repeat (/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:509:21)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DmitryTsyganov** [comment]
После #30 исправлено
