### ISSUE TITLE
traversDST can pass null to visit() callback

### ISSUE THREAD

**Issue by DmitryTsyganov** [nochgames/server#6]
/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:104
        clearInterval(node.intervalID);
                          ^

TypeError: Cannot read property 'intervalID' of null
    at BasicParticle.free (/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:104:27)
    at Object.BasicParticle.traversDST (/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:63:9)
    at Object.Player.dismountBranch (/home/fatman/WebstormProjects/server/gamemechanics/player/index.js:139:14)
    at Object.BasicParticle.changeCharge (/home/fatman/WebstormProjects/server/gamemechanics/basic particle/index.js:407:18)
    at Object.Player.shoot (/home/fatman/WebstormProjects/server/gamemechanics/player/index.js:76:39)
    at WebSocket.<anonymous> (/home/fatman/WebstormProjects/server/websocketservice/index.js:85:28)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.ontext (/home/fatman/WebstormProjects/server/node_modules/ws/lib/WebSocket.js:816:10)
    at /home/fatman/WebstormProjects/server/node_modules/ws/lib/Receiver.js:477:18

**Comment by DmitryTsyganov** [comment]
Problem was in garbagify() method - it can't change prototype, therefore Player methods were called instead of Garbage methods

**Comment by DmitryTsyganov** [comment]
Now it passes undefined

**Comment by DmitryTsyganov** [comment]
Fix for passing undefined in basic particle:

``` javascript
let child = null;
while (!child) {
    child = this.body.chemicalChildren.pop();
}
if (!child) throw new Error('Incorrect behaviour');
```
