### ISSUE TITLE
context.getMainObject(body) frequantly returns undefined

### ISSUE THREAD

**Issue by DmitryTsyganov** [nochgames/server#7]
/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:148
        this.context.getMainObject(elementBody).changeCharge(1, this.context.engine, this.context.freeProtons);
                                               ^

TypeError: Cannot read property 'changeCharge' of undefined
    at Object.CollisionHandler.collideWithProton (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:148:48)
    at Object.<anonymous> (/home/fatman/WebstormProjects/server/gamemechanics/collision_handler.js:40:22)
    at Object.Events.trigger (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4985:38)
    at Object.Engine.update (/home/fatman/WebstormProjects/server/node_modules/matter-js/build/matter.js:4474:20)
    at null._repeat (/home/fatman/WebstormProjects/server/gamemechanics/index.js:357:27)
    at wrapper [as _onTimeout](timers.js:275:19)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by DmitryTsyganov** [comment]
The problem was in basicParticle.checkDecoupling(). It could call basicParticle.free() for player making his inGameType 'garbage'. So recycleBin deleted garbage with same index instead of player.
This addition in free() solves problem:

``` javascript
        if (node.inGameType != 'player') {
            node.inGameType = "garbage";
            node.playerNumber = -1175;
        }
```
